FROM mcr.microsoft.com/dotnet/sdk:10.0-alpine AS build
WORKDIR /source
COPY . .
RUN dotnet restore src/SentinelPay.ProviderSimulator/SentinelPay.ProviderSimulator.csproj
RUN dotnet publish src/SentinelPay.ProviderSimulator/SentinelPay.ProviderSimulator.csproj \
    --configuration Release \
    --no-restore \
    --output /app/publish \
    /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0-alpine AS final
WORKDIR /app
COPY --from=build /app/publish .
USER app
EXPOSE 8080
ENV ASPNETCORE_HTTP_PORTS=8080
ENTRYPOINT ["dotnet", "SentinelPay.ProviderSimulator.dll"]
